# Generated by Django 3.2.9 on 2021-11-04 13:58

import acl_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15, validators=[acl_user.models.validate_empty_first_name])),
                ('last_name', models.CharField(max_length=15)),
                ('phone', models.CharField(default='+6282637778888', max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
